name: VoteKick
main: io.github.yuhiych.votekick.VoteKick
version: 2.0
softdepend: [PlaceholderAPI]
commands:
    vk:
        usage: /<command>
        description: Help
permissions:
    votekick.vote:
        description: vote
        default: true
    votekick.bypass:
        description: bypass
        default: op
    votekick.admin:
        description: admin
        default: op